import Head from 'next/head'
import { useState } from 'react';

import dynamic from "next/dynamic";
const RenderLineChart = dynamic(() => import('./chart/line'), { ssr: false });


export default function Home() {
  const [temp, setTemp] = useState()
  const [humidity, setHumidity] = useState()
  const [newTemp, setNewtemp] = useState([])
  const submit = () => {
    setNewtemp({
      temperature: Number(temp),
      humidity: Number(humidity),
    })
  }
  return (
    <>
      <Head>
        <title>LinearRegression</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-white h-screen'>
        <div className="flex justify-center flex-col space-y-10">
          <h1 className="text-black text-5xl text-center">Linear Regression </h1>
          <div className="flex justify-center space-x-5 h-14 items-center">
            <label className="text-black">รับข้อมูลอุณหภูมิ</label>
            <input type="number" className="outline-none h-full pl-4 bg-gray[50] rounded-xl w-[30rem]" onChange={(e) => setTemp(e.target.value)} />
            <label className="text-black">รับข้อมูลความชื้น</label>
            <input type="number" className="outline-none  h-full pl-4 bg-gray[50] rounded-xl w-[30rem]" onChange={(e) => setHumidity(e.target.value)} />
          </div>
          <div className="flex justify-center items-center flex-col space-y-10">
            <button className='bg-sky-500 text-black h-10 w-16 rounded-xl' onClick={() => submit()}>Submit</button>

            <RenderLineChart data={newTemp} />
          </div>
        </div>
      </div>
    </>
  )
}
